### PR TITLE
Update tutorials formatting

### PR DESCRIPTION
**Pull request by damonbayer**
See https://github.com/CDCgov/multisignal-epi-inference/issues/159.

### CODE REVIEW

**Comment by dylanhmorris** [comment]
Confirming this does _not_ close #159, correct?

**Comment by damonbayer** [comment]
@dylanhmorris That's correct. I only linked to https://github.com/CDCgov/multisignal-epi-inference/issues/159 to explain why it was not done automatically.

**Comment by sbidari** [comment]
I am confused. Is this formatting done automatically, or no? @damonbayer @dylanhmorris

**Comment by damonbayer** [comment]
It can be done semi-automatically in VS Code. However, it only works on a cell-by-cell basis, so you have to go through each cell and issue a formatting command (or re-save the document if you have format on save enabled). As far as I know, there is no way to format an entire `qmd` at once, but that would be really nice to have in pre-commit.

**Review by dylanhmorris — APPROVED** [review]
LGTM

**Pull request merged**
