### PR TITLE
Adding Repository Structure And Resources Sections To The README

### PR DESCRIPTION
**Pull request by AFg6K7h4fhy2**
This is a small pull request that adds two simple items to the README file: the structure of the MSR repository via `tree` and a Resources section. 

A Repository Structure section enables users to get an impression of the MSR repository very quickly. While MSR's structure will change, requiring the Repository Structure section of the README to be manually revised, revisions need not be done frequently, since the design of MSR currently is such that further updates are unlikely to deviate significantly enough for the existing but outdated `tree` output to cease to be useful. The only request I have here for reviewers is to provide some thoughts for what to ignore when running `tree`.

Resources are helpful for newcomers and for those who've forgotten where to find particular items relevant to the project. I have added four resources. More resources can be added by others, including the reviewers. 

As for the placement of the sections in the README, I thought that after the General Disclaimer worked well, since Public Domain Standard Notice becomes less MSR and or CDC specific.

### CODE REVIEW

**Comment by damonbayer** [comment]
Thanks, Trevor. I agree adding more content to help people get oriented would be helpful.

Re: the MSR Relevant Resources, one sentence or fragment about each resource would be helpful (e.g. For an intro to `x`, we recommend `y`.

Re: the tree structure, I think anything related to the internal structure of the repo would be better suited for [our developer documentation](https://github.com/CDCgov/multisignal-epi-inference/issues/7). Maybe we can remove it from this PR and add a note to that issue, if you agree. In that case, I might suggest we only give the command to print the `tree` and omit the output of the command.

**Review by damonbayer — CHANGES_REQUESTED** [review]
Thanks, Trevor! I agree that adding more content to help people get oriented would be helpful.

Re: the MSR Relevant Resources, one sentence or fragment about each resource would be helpful (e.g. For an intro to `x`, we recommend `y`.

Re: the tree structure, I think anything related to the internal structure of the repo would be better suited for [our developer documentation](https://github.com/CDCgov/multisignal-epi-inference/issues/7). Maybe we can remove it from this PR and add a note to that issue, if you agree. In that case, I might suggest we only give the command to print the `tree` and omit the output of the command.

**Comment by AFg6K7h4fhy2** [comment]
@damonbayer I agree with you that a one sentence description can help. I still believe that having the repository structure displayed in the README would be a net good (perhaps if a Last Updated: YYYY-MM-DD) if provided _somewhere_. I am fine with this _somewhere_ being the developer documentation while leaving a note on how to display the structure for oneself, as you suggested.

**Review by sbidari — COMMENTED** [review]
Thanks Trevor! These resources would be helpful to newcomers. 
Agree with @damonbayer Re including a sentence or more about the resources. 

I think the model equation sheet could be moved to the documentation along with a brief introduction to the renewal model.

**Comment by AFg6K7h4fhy2** [comment]
If this 

> I think the model equation sheet could be moved to the documentation along with a brief introduction to the renewal model.

expected to be covered in #191 ? 

@sbidari

**Comment by sbidari** [comment]
> Is this
> 
> > I think the model equation sheet could be moved to the documentation along with a brief introduction to the renewal model.
> 
> expected to be covered in #191 ?
> 
> @sbidari

Yes, just requested review for some proposed changes in documentation.

**Review by damonbayer — APPROVED** [review]

**Pull request merged**
