### PR TITLE
improve x-axis label

### LINKED ISSUE #285: Improve admissions data x-tick labels in `hospital_admissions_model.qmd`
> Not changed in this PR, but could we improve the x-axis tick labels for the first figure?
image

_Originally posted by @damonbayer in https://github.com/CDCgov/multisignal-epi-inference/pull/281#discussion_r1684814144_

### PR DESCRIPTION
**Pull request by sbidari**
Closes #285

### CODE REVIEW

**Comment by sbidari** [comment]
https://github.com/CDCgov/multisignal-epi-inference/pull/299/files#diff-cbf0760f0ebe10192aed2cba5d69b3bedb6bbc54188905bf79b9b8c7d310efc9L270

Was this supposed to be `axs[1].plot(simulated_data.observed_hosp_admissions, "o")`?

**Comment by damonbayer** [comment]
> https://github.com/CDCgov/multisignal-epi-inference/pull/299/files#diff-cbf0760f0ebe10192aed2cba5d69b3bedb6bbc54188905bf79b9b8c7d310efc9L270
> 
> Was this supposed to be `axs[1].plot(simulated_data.observed_hosp_admissions, "o")`?

No. I think we wanted both the lines and the dots.

**Comment by dylanhmorris** [comment]
Would be nice to bring back the 45º tick label rotation if possible.

**Comment by dylanhmorris** [comment]
> No. I think we wanted both the lines and the dots.

Related: the plot whose date formatting we're fixing might also benefit from the `"-o"` lines-and-dots style.

**Comment by sbidari** [comment]
> Would be nice to bring back the 45º tick label rotation if possible. Right now, dates render nicely but are vertical:
Screenshot 2024-07-23 132416
I thought this made it less clear which tick the label correspond to, but I can revert back to 45 degrees rotation!

**Comment by damonbayer** [comment]
> I thought this made it less clear which tick the label correspond to, but I can revert back to 45 degrees rotation!

I agree this is less readable. I think I would prefer fewer labels. Maybe one every 4 weeks.

**Comment by dylanhmorris** [comment]
You can also re-anchor the ticks so that they better correspond to individual ticks: https://stackoverflow.com/questions/14852821/aligning-rotated-xticklabels-with-their-respective-xticks

**Comment by sbidari** [comment]
I changed the plot to line and dot style with axis labels rotated to 45 degrees with fewer labels (every 2 weeks)

**Review by damonbayer — CHANGES_REQUESTED** [review]
@sbidari I think we should follow the advice of [this answer](https://stackoverflow.com/a/67459618), which is to use `ha='right` and  `rotation_mode='anchor'`.

**Comment by sbidari** [comment]
add label for every week? @damonbayer

**Comment by damonbayer** [comment]
> add label for every week? @damonbayer

I think so, but feel free to use your own judgement, if you think it is too hard to read.

**Review by damonbayer — APPROVED** [review]
Thanks @sbidari!

**Pull request merged**
