### PR TITLE
Additional `seed` To `init` Changes

### PR DESCRIPTION
**Pull request by AFg6K7h4fhy2**
> The author of this issue recently found some `seed` names that had missed being changed (e.g. `I_pre_seed` and `I_pre_seed_rv`). These are now to be changed to `init` with permission from @damonbayer.

### CODE REVIEW

**Review by damonbayer — CHANGES_REQUESTED** [review]
I still see some `seed` usage in `time.qmd` and `model/src/pyrenew/latent/infection_initialization_method.py` and `model/src/pyrenew/latent/infection_initialization_process.py`

**Comment by AFg6K7h4fhy2** [comment]
Screenshot 2024-07-23 at 15 09 09

Confirming that what you are seeing concerns descriptions and not code. I was under the impression that some descriptions involving seeding were okay so long as any confusion was reconciled for users via `init` or `initialization` being used over `seed` or `seeding` in code.

**Comment by damonbayer** [comment]
> Confirming that what you are seeing concerns descriptions and not code? I was under the impression that some descriptions involving seeding were okay so long as any confusion was reconciled for users via `init` or `initialization` being used over `seed` or `seeding` in code.

Yes, I am referring to the comments. I will change them and then merge. Thanks for catching this @AFg6K7h4fhy2!

**Review by damonbayer — APPROVED** [review]
Thanks @AFg6K7h4fhy2!

**Pull request merged**
