### PR TITLE
Record deterministic `RandomVariables` by default

### PR DESCRIPTION
**Pull request by damonbayer**
Closes https://github.com/CDCgov/multisignal-epi-inference/issues/127

### CODE REVIEW

**Comment by dylanhmorris** [comment]
If `record=True` is going to be the default (and I think it should be, though I'm persuadable), then I think `label` should not have a default argument, as this will make it easy for the user to end up with variable name collisions, as occurs in the test suite here:

```
E       AssertionError: all sites must have unique names but got `a_random_variable` duplicated
```

Also, since the `label` attribute will be passed to `numpyro.deterministic()` as the `name` argument, I think it should be renamed `name` for consistency.

https://github.com/CDCgov/multisignal-epi-inference/blob/83dd9ddf11df1b0e5a5059f34fb7e1a84e466b9e/model/src/pyrenew/deterministic/deterministic.py#L17-L29

**Comment by damonbayer** [comment]
@dylanhmorris @gvegayon Ready for review, but expecting many merge conflicts, depending on when other PR's land.

**Review by gvegayon — APPROVED** [review]
Looks good! One minor comment. Should we be more explicit about key word arguments? I feel like we should try to enforce (at least internally and during tutorials) using keywords instead of passing arguments as is. We could deal with this in another issue later.

cc @dylanhmorris

**Review by dylanhmorris — APPROVED** [review]
LGTM!

**Pull request merged**
