### PR TITLE
Make concentration in `NegativeBinomialObservation` a `RandomVariable`

### PR DESCRIPTION
**Pull request by damonbayer**
Closes https://github.com/CDCgov/multisignal-epi-inference/issues/178.
Partially addresses https://github.com/CDCgov/multisignal-epi-inference/issues/198.

I now also estimate the overdipsersion parameter in `hospital_admissions_model.qmd`.
This makes the inference take quite a while, so maybe we should look at reducing the scope of that tutorial.
It leads to a nice-looking posterior predictive:
fig-output-posterior-predictive-output-1

But funky looking posterior latent infections:
fig-output-infections-distribution-output-1

Not sure if this is just an artifact of the hdi plots or if it indicates something undesirable about the model.

### CODE REVIEW

**Comment by sbidari** [comment]
@damonbayer did you also look at equal tailed intervals for the posterior latent infection?

**Comment by damonbayer** [comment]
> @damonbayer did you also look at equal tailed intervals for the posterior latent infection?

No. I would accept a contribution for that figure, though :)

**Comment by dylanhmorris** [comment]
Caught the problem in #269 from looking at the example figures highlighted here by @damonbayer. Suggest landing that first and merging it in here.

**Comment by damonbayer** [comment]
@dylanhmorris https://github.com/CDCgov/multisignal-epi-inference/pull/269 is merged here

**Review by dylanhmorris — APPROVED** [review]
LGTM

**Comment by sbidari** [comment]
The posterior plots in this tutorial doesn't look right. Looks like the posterior samples are all just same array?
Capture1
and the diagnostics are bad
Capture

**Comment by damonbayer** [comment]
There is some variability in latent infections (see my original post), but I agree it is strange.

**Comment by sbidari** [comment]
There is no within chain variability in the posterior samples

**Comment by dylanhmorris** [comment]
The prior on the concentration is not working as written. I tried swapping in a LogNormal prior and things just worked. Will investigate further.

**Pull request merged**
