### PR TITLE
Create typos.yaml

### PR DESCRIPTION
**Pull request by natemcintosh**
Helps us keep things spelled correctly in the repo

### CODE REVIEW

**Comment by gvegayoncdc** [comment]
There's a [pre-commit hook](https://github.com/crate-ci/typos/blob/6233184298a40671ccdd63744fce6209c38df06d/docs/pre-commit.md) too. Should we add that as well?

**Comment by natemcintosh** [comment]
Yea, I was just thinking that. I think if it lives in pre-commit, it probably doesn't need its own workflow

**Comment by natemcintosh** [comment]
Looks like it found a few. Already useful!

**Review by gvegayoncdc — APPROVED** [review]

**Comment by gvegayoncdc** [comment]
Thank you!

**Comment by gvegayoncdc** [comment]
@dylanhmorris, can you set up the auto-delete and squash and merge by default? I would, but I don't have admin access to the repo.

**Pull request merged**
