### PR TITLE
Renaming The Infections Seeding Initialization

### PR DESCRIPTION
**Pull request by AFg6K7h4fhy2**
This PR clarifies naming for $I_{v:0}$, i.e. the seeded infections, by framing the variable for infections seeding in terms of "initialization" versus "seeding", which, in most instances, is perceived by users as the value for pseudo-random number generation reproducibility.

### CODE REVIEW

**Review by damonbayer — CHANGES_REQUESTED** [review]
Thanks @AFg6K7h4fhy2! I think we should perform more renaming throughout. For instance, `InfectionSeedingProcess` should be `InfectionInitializationProcess`. In general, you should search the whole repo for `seed` and make sure it is only used in the context of RNG seeds. @dylanhmorris do you agree?

**Comment by AFg6K7h4fhy2** [comment]
> Thanks @AFg6K7h4fhy2! I think we should perform more renaming throughout. For instance, `InfectionSeedingProcess` should be `InfectionInitializationProcess`. In general, you should search the whole repo for `seed` and make sure it is only used in the context of RNG seeds. @dylanhmorris do you agree?

I agree. I held because I didn't want to decide unilaterally. Beyond `InfectionSeedingProcess`, I am thinking any other place where we have `Infection` and `Seeding` not in reference to pseudo-random number usage.

**Comment by dylanhmorris** [comment]
> Thanks @AFg6K7h4fhy2! I think we should perform more renaming throughout. For instance, InfectionSeedingProcess should be InfectionInitializationProcess. In general, you should search the whole repo for seed and make sure it is only used in the context of RNG seeds. @dylanhmorris do you agree?

I do. @AFg6K7h4fhy2, I think you can assume `initialization` is the agreed-upon substitute for `seeding` throughout.

**Comment by AFg6K7h4fhy2** [comment]
> I do. @AFg6K7h4fhy2, I think you can assume `initialization` is the agreed-upon substitute for `seeding` throughout.

Sounds good, I will edit this after I get through #241

**Comment by damonbayer** [comment]
Thanks @AFg6K7h4fhy2! I prefer `post_initialization_infections` over `post_initialized_infections`.

**Comment by AFg6K7h4fhy2** [comment]
> Thanks @AFg6K7h4fhy2! I prefer `post_initialization_infections` over `post_initialized_infections`.
> 
> The documentation, for example `docs/source/msei_reference/latent.rst`, also needs to be changed.

Will do on `post_initialized_infections` &rarr; `post_initialization_infections`. Good catch on the `./docs/` changes. I think I was one level off when doing `Command-Shift-F`.

**Comment by damonbayer** [comment]
I think we also want to rename the `InfectionInitializationMethod`s (e.g., `SeedInfectionsExponentialGrowth -> InitializeInfectionsExponentialGrowth`).

**Comment by AFg6K7h4fhy2** [comment]
> I think we also want to rename the `InfectionInitializationMethod`s (e.g., `SeedInfectionsExponentialGrowth -> InitializeInfectionsExponentialGrowth`).

I was thinking that since they were subclasses the connection with seeding infections shouldn't be completely removed, but I see the point. Will change.

**Review by damonbayer — APPROVED** [review]
Looks good. Thanks @AFg6K7h4fhy2!

**Pull request merged**
